---
- name: configuring the apache server
  hosts: myserver
  become: yes
  tasks:
    - name: Install prerequisites
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'aptitude' ]
    - name: installing the apache packages
      apt:
        name: apache2
        state: present
    - name: starting apache services
      service:
        name: apache2
        state: started
    - name: Copy file to remote server
      copy:
       src: /tmp/calculator
       dest: /tmp/calculator
       remote_src: true

    - name: restarting the apache services
      service:
        name: apache2
        state: restarted
